### ISSUE TITLE
Directory missing at compile time

### ISSUE THREAD

**Issue by Adahai** [mhaseeb123/nvstdpar#48]
I ran into some problems when compiling the fft unit. The steps are as follows
step0: git checkout main
step1: apps/fft
step2: g++ fft-serial.cpp fft-stdexec.cpp fft-stdpar.cpp -o fft
The error is as follows:
fatal error: experimental/mdspan: No such file or directory
How can I fix this?

**Comment by mhaseeb123** [comment]
Hi, @Adahai 

Thank you for reaching out. This repos is intended to build with the NVC++ and CUDA compilers. Assuming that you only want to build the FFT code with GCC, here's what you can do:

```bash
git clone --recursive https://github.com/mhaseeb123/nvstdpar.git
```bash
cd nvstdpar/apps/fft

Replace the `fft.hpp`, `fft-serial.cpp` and `fft-stdpar.cpp` with the ones inside the attached [files.zip](https://github.com/mhaseeb123/nvstdpar/files/13160487/files.zip), and now build:

# build the serial fft version
g++  -std=c++20 -o fft-serial ./fft-serial.cpp -I ../../include/  -I ../../externals/argparse/include/ -I ../../externals/mdspan/include -I ../../../../stdexec/include/
```

# build the parallel version (you will need libtbb installed for this)
g++ -std=c++20 -o fft-stdpar ./fft-stdpar.cpp -I ../../include/  -I ../../externals/argparse/include/ -I ../../externals/mdspan/include -I ../../../../stdexec/include/ -L/path/to/libtbb.a -ltbb
[files.zip](https://github.com/mhaseeb123/nvstdpar/files/13160485/files.zip)

**Note**: I have removed the timer and some other features from this to simply the compilation. You are free to remove more features like argparse, mdspan as per your needs.

**Comment by mhaseeb123** [comment]
@Adahai please let me know if the above instructions solved your problem.
